[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false
idl-build = ["anchor-lang/idl-build"]

[programs.localnet]
relay = "5ZeMSd6ot2FPBBAt1s4hF3ffKAjNvp1LvFNT62FPqQCi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chakravarti/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
